// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationExcelMembership
    {
        public int No { get; set; }
        public System.DateTime? Date { get; set; }
        public string Agreement { get; set; }
        public string AgreementFix { get; set; }
        public string MemberName { get; set; }
        public System.DateTime? DateOfBirth { get; set; }
        public string Telp { get; set; }
        public string MembershipType { get; set; }
        public string Membership { get; set; }
        public string Prefix { get; set; }
        public int? TotalMonth { get; set; }
        public string RecordType { get; set; }
        public System.DateTime? EFD { get; set; }
        public System.DateTime? EXP { get; set; }
        public decimal? Paid1 { get; set; }
        public decimal? Paid2 { get; set; }
        public decimal? Paid3 { get; set; }
        public string By1 { get; set; }
        public string By2 { get; set; }
        public string Sold { get; set; }
        public string Remarks { get; set; }
        public string Address { get; set; }
        public bool? GymBag { get; set; }
        public bool? Tshirt { get; set; }
        public string Bank { get; set; }
        public string Payment { get; set; }

    }

}
// </auto-generated>
