// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtestprocedureReturnModel
    {
        public System.Int32 MemberID { get; set; }
        public System.String MemberNO { get; set; }
        public System.Int32 PersonID { get; set; }
        public System.DateTime MMulai { get; set; }
        public System.Byte[] MFoto { get; set; }
        public System.Byte[] MFotoKTP { get; set; }
        public System.Byte[] MFotoCCDebit { get; set; }
        public System.Byte[] MFotoSignature { get; set; }
        public System.String MRFID { get; set; }
        public System.Int32? MemberTypeID { get; set; }
        public System.Int32? TotalMonth { get; set; }
    }

}
// </auto-generated>
