// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class Validationlog
    {
        public int id { get; set; }
        public System.DateTime? date { get; set; }
        public string identity { get; set; }
        public string level { get; set; }
        public string logger { get; set; }
        public string message { get; set; }
        public string timestamp { get; set; }
        public string type { get; set; }
        public string username { get; set; }
        public System.DateTime? utcdate { get; set; }
        public string IdTable { get; set; }
        public string NamaTransaksi { get; set; }
        public string NamaTable { get; set; }
        public string exception { get; set; }



    }

}
// </auto-generated>
