// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51

using System;
using System.Web.Mvc;
using Services.Attribute;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtPerson
    {
        public int PersonID { get; set; }

        [Required(ErrorMessage = "Nama Tidak boleh kosong")]
        public string PNama { get; set; }
        public string PTempLahir { get; set; }

        [TrippleDDLDateTime(ErrorMessage = "Tanggal lahir tidak tepat")]
        [CustomAttribute()]
        public System.DateTime? PTglLahir { get; set; }

        public string PGender { get; set; }

        [Required(ErrorMessage = "Alamat di perlukan")]
        public string PAlamat { get; set; }

        public string PRT { get; set; }
        public string PRW { get; set; }
        public string PKelurahan { get; set; }
        public string PKecamatan { get; set; }
        public string PKota { get; set; }
        public string PPropinsi { get; set; }

        [Required(ErrorMessage = "Identitas tidak boleh kosong")]
        public string PIdentitas { get; set; }
        public string PEmail { get; set; }

        public string PTelp { get; set; }

        [Required(ErrorMessage = "TELP / HP Di perlukan")]
        public string PHP1 { get; set; }

        public string PHP2 { get; set; }
        public string PPinBB { get; set; }
        public string Id { get; set; }

    }

}
// </auto-generated>
