// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtrPaymentWith
    {
        public int PaymentWithID { get; set; }
        public int PaymentTypeID { get; set; }
        public int? BankID { get; set; }
        public int? EDCID { get; set; }
        public string ApprCode { get; set; }
        public string TraceCode { get; set; }
        public string Pemegang { get; set; }
        public string NoKartu { get; set; }
        public System.DateTime? ValidUntil { get; set; }
        public decimal payAmount { get; set; }
        public decimal? paidAmount { get; set; }
        public decimal? MBRAmount { get; set; }



    }

}
// </auto-generated>
