// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtrPlanAktifitasPT
    {
        public int PlanAktifitasPTID { get; set; }
        public int DayOfWeek { get; set; }
        public string period { get; set; }
        public System.TimeSpan WaktuMulai { get; set; }
        public System.TimeSpan WaktuSelesai { get; set; }
        public int LocationID { get; set; }
        public int MemberID { get; set; }
        public int PersonBOIDPT { get; set; }
        public int PersonBOID { get; set; }
        public string Note { get; set; }

    }

}
// </auto-generated>
