// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51

using System.ComponentModel.DataAnnotations;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    public partial class ValidationStrActionKlaimParam
    {
        //        public int IdPar { get; set; }
        //        public int StrActionClaimId { get; set; }
        //        public string NamaParam { get; set; }
        //        public string Satuan { get; set; }
        //        public string Value { get; set; }


        partial void InitializePartial();
    }

}
// </auto-generated>
