// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtUserBackOffice
    {
        public int PersonBOID { get; set; }
        public string BOIDNO { get; set; }
        public bool StatusBOID { get; set; }
        public System.DateTime BMulai { get; set; }
        public byte[] BFoto { get; set; }
        public byte[] BFotoKTP { get; set; }
        public byte[] BFotoSignature { get; set; }
        public string BRFID { get; set; }
        [Required]
        public int PosisiID { get; set; }
        public string Background { get; set; }


    }

}
// </auto-generated>
