// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtMemberType
    {
        public int MemberTypeID { get; set; }
        public string MemberType { get; set; }
        public decimal Biaya { get; set; }
        [Display(Name ="Total Bulan")]
        public int JmlBulan { get; set; }
        public bool IsPaket { get; set; }
        public int Share { get; set; }
        public int? ShareMin { get; set; }
        public string Periode { get; set; }

        [Display(Name ="Location")]
        public int? LocationID { get; set; }
        public string prFix { get; set; }
        public decimal? Admin { get; set; }
        public decimal? Prorate { get; set; }
        public bool Status { get; set; }

        [Display(Name ="Paket Personal Trainer")]
        public int? tPaketPersonalTrainerID { get; set; }

    }

}
// </auto-generated>
