// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtrAktifitasMember
    {
        public int AktifitasMemberID { get; set; }
        public System.DateTime? AMMulai { get; set; }
        public System.DateTime? AMSelesai { get; set; }
        public string verifikasiMember { get; set; }
        public string verifikasiToken { get; set; }
        public int MemberID { get; set; }
        public int PersonBOID { get; set; }
        public int LocationID { get; set; }
        public int? ActionPTID { get; set; }
        public string Status { get; set; }
    }

}
// </auto-generated>
