// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataValidator.Validation
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ValidationtrPersonalTrainer
    {
        public int trPersonalTrainerID { get; set; }
        public int tPaketPTID { get; set; }
        public int? SisaJam { get; set; }
        public int PersonBOIDPT { get; set; }
        public int seq { get; set; }
        public int? ParentID { get; set; }
        public int? trMembershipID { get; set; }

    }

}
// </auto-generated>
