// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Interfaces
{
    using DataObjects.Entities;

    public interface IFitEntity : System.IDisposable
    {
        System.Data.Entity.DbSet<ApplicationGroup> ApplicationGroups { get; set; }
        System.Data.Entity.DbSet<ApplicationGroupRole> ApplicationGroupRoles { get; set; }
        System.Data.Entity.DbSet<ApplicationUserGroup> ApplicationUserGroups { get; set; }
        System.Data.Entity.DbSet<AspForm> AspForms { get; set; }
        System.Data.Entity.DbSet<AspFormAuthorization> AspFormAuthorizations { get; set; }
        System.Data.Entity.DbSet<AspNetRole> AspNetRoles { get; set; }
        System.Data.Entity.DbSet<AspNetUser> AspNetUsers { get; set; }
        System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        System.Data.Entity.DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        System.Data.Entity.DbSet<ExcelLipo5> ExcelLipo5 { get; set; }
        System.Data.Entity.DbSet<ExcelPT> ExcelPTs { get; set; }
        System.Data.Entity.DbSet<ExcelUploadDB> ExcelUploadDBs { get; set; }
        System.Data.Entity.DbSet<log> logs { get; set; }
        System.Data.Entity.DbSet<Logtest> Logtests { get; set; }
        System.Data.Entity.DbSet<stMemberFingerPrint> stMemberFingerPrints { get; set; }
        System.Data.Entity.DbSet<StrActionKlaim> StrActionKlaims { get; set; }
        System.Data.Entity.DbSet<StrActionKlaimParam> StrActionKlaimParams { get; set; }
        System.Data.Entity.DbSet<strAktivitasSale> strAktivitasSales { get; set; }
        System.Data.Entity.DbSet<strKlaimPT> strKlaimPTs { get; set; }
        System.Data.Entity.DbSet<strLocBO> strLocBOes { get; set; }
        System.Data.Entity.DbSet<strLocMember> strLocMembers { get; set; }
        System.Data.Entity.DbSet<strPayment> strPayments { get; set; }
        System.Data.Entity.DbSet<strPaymentMember> strPaymentMembers { get; set; }
        System.Data.Entity.DbSet<strPersonEvent> strPersonEvents { get; set; }
        System.Data.Entity.DbSet<sysdiagram> sysdiagrams { get; set; }
        System.Data.Entity.DbSet<tActionPT> tActionPTs { get; set; }
        System.Data.Entity.DbSet<tBank> tBanks { get; set; }
        System.Data.Entity.DbSet<tCardStatu> tCardStatus { get; set; }
        System.Data.Entity.DbSet<tEvent> tEvents { get; set; }
        System.Data.Entity.DbSet<tEventScore> tEventScores { get; set; }
        System.Data.Entity.DbSet<tEventStep> tEventSteps { get; set; }
        System.Data.Entity.DbSet<tKela> tKelas { get; set; }
        System.Data.Entity.DbSet<tLocFitnessCenter> tLocFitnessCenters { get; set; }
        System.Data.Entity.DbSet<tMember> tMembers { get; set; }
        System.Data.Entity.DbSet<tMemberState> tMemberStates { get; set; }
        System.Data.Entity.DbSet<tMemberType> tMemberTypes { get; set; }
        System.Data.Entity.DbSet<tPaketPT> tPaketPTs { get; set; }
        System.Data.Entity.DbSet<tPaymentType> tPaymentTypes { get; set; }
        System.Data.Entity.DbSet<tPerson> tPersons { get; set; }
        System.Data.Entity.DbSet<tPosisi> tPosisis { get; set; }
        System.Data.Entity.DbSet<trAktifitasKela> trAktifitasKelas { get; set; }
        System.Data.Entity.DbSet<trAktifitasMember> trAktifitasMembers { get; set; }
        System.Data.Entity.DbSet<trCinCout> trCinCouts { get; set; }
        System.Data.Entity.DbSet<trEventScore> trEventScores { get; set; }
        System.Data.Entity.DbSet<trEventStep> trEventSteps { get; set; }
        System.Data.Entity.DbSet<trMembership> trMemberships { get; set; }
        System.Data.Entity.DbSet<tRoleEvent> tRoleEvents { get; set; }
        System.Data.Entity.DbSet<trPaymentWith> trPaymentWiths { get; set; }
        System.Data.Entity.DbSet<trPembayaran> trPembayarans { get; set; }
        System.Data.Entity.DbSet<trPersonalTrainer> trPersonalTrainers { get; set; }
        System.Data.Entity.DbSet<trPersonEvent> trPersonEvents { get; set; }
        System.Data.Entity.DbSet<trPlanAktifitasPT> trPlanAktifitasPTs { get; set; }
        System.Data.Entity.DbSet<trPlanKela> trPlanKelas { get; set; }
        System.Data.Entity.DbSet<trTTD> trTTDs { get; set; }
        System.Data.Entity.DbSet<tRuangKela> tRuangKelas { get; set; }
        System.Data.Entity.DbSet<tSalesAction> tSalesActions { get; set; }
        System.Data.Entity.DbSet<tStatusMember> tStatusMembers { get; set; }
        System.Data.Entity.DbSet<tStatusMemberPrice> tStatusMemberPrices { get; set; }
        System.Data.Entity.DbSet<tTypeStatusCinCout> tTypeStatusCinCouts { get; set; }
        System.Data.Entity.DbSet<tUserBackOffice> tUserBackOffices { get; set; }

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        
        // Stored Procedures
        System.Collections.Generic.List<testprocedureReturnModel> testprocedure();
        System.Collections.Generic.List<testprocedureReturnModel> testprocedure(out int procResult);
        int Tool_ScriptDiagram(string name);
        int Tool_ScriptDiagram2005(string name);
    }

}
// </auto-generated>
