// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationApplicationGroup))]
    public partial class ApplicationGroup
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }

        public virtual System.Collections.Generic.ICollection<ApplicationGroupRole> ApplicationGroupRoles { get; set; }
        public virtual System.Collections.Generic.ICollection<ApplicationUserGroup> ApplicationUserGroups { get; set; }
        public virtual System.Collections.Generic.ICollection<AspFormAuthorization> AspFormAuthorizations { get; set; }

        public ApplicationGroup()
        {
            ApplicationGroupRoles = new System.Collections.Generic.List<ApplicationGroupRole>();
            ApplicationUserGroups = new System.Collections.Generic.List<ApplicationUserGroup>();
            AspFormAuthorizations = new System.Collections.Generic.List<AspFormAuthorization>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
