// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationAspForm))]
    public partial class AspForm
    {
        public int FormId { get; set; }
        public int? parent_ID { get; set; }
        public string MasterModule { get; set; }
        public string Module { get; set; }
        public string title { get; set; }
        public string desciption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string url { get; set; }
        public string area { get; set; }
        public bool? visible { get; set; }
        public string parameter { get; set; }
        public bool? clickable { get; set; }
        public string statusCode { get; set; }
        public int? displayOrder { get; set; }
        public string iconclass { get; set; }
        public bool? Parent { get; set; }

        public virtual System.Collections.Generic.ICollection<AspForm> AspForms { get; set; }
        public virtual System.Collections.Generic.ICollection<AspFormAuthorization> AspFormAuthorizations { get; set; }

        public virtual AspForm AspForm_parent_ID { get; set; }

        public AspForm()
        {
            AspForms = new System.Collections.Generic.List<AspForm>();
            AspFormAuthorizations = new System.Collections.Generic.List<AspFormAuthorization>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
