// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationAspFormAuthorization))]
    public partial class AspFormAuthorization
    {
        public int authID { get; set; }
        public int FormID { get; set; }
        public string GroupId { get; set; }

        public virtual ApplicationGroup ApplicationGroup { get; set; }
        public virtual AspForm AspForm { get; set; }

        public AspFormAuthorization()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
