// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public partial class ExcelLipo5
    {
        public int No { get; set; }
        public string Agreement { get; set; }
        public string AgreementFix { get; set; }
        public string MemberName { get; set; }
        public string MembershipType { get; set; }
        public string MembershipPrFix { get; set; }
        public string MembershipFix { get; set; }
        public int? Monthly { get; set; }
        public string Note { get; set; }

        public ExcelLipo5()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
