// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
    using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public partial class ExcelPT
    {
        public int No { get; set; }
        public System.DateTime? Date { get; set; }
        public string Aggrement { get; set; }
        public string Nama { get; set; }
        public System.DateTime? DOB { get; set; }
        public string Telp { get; set; }
        public string Type { get; set; }
        public int? LongTime { get; set; }
        public System.DateTime? EFD { get; set; }
        public System.DateTime? EXP { get; set; }
        public decimal? Paid { get; set; }
        public decimal? Paid2 { get; set; }
        public string By1 { get; set; }
        public string By2 { get; set; }
        public string Remark { get; set; }
        public string Address { get; set; }

        public ExcelPT()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
