// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationStrActionKlaimParam))]
    public partial class StrActionKlaimParam
    {
        public int IdPar { get; set; }
        public int StrActionClaimId { get; set; }
        public string NamaParam { get; set; }
        public string Satuan { get; set; }
        public string Value { get; set; }

        public virtual StrActionKlaim StrActionKlaim { get; set; }

        public StrActionKlaimParam()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
