// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationstrAktivitasSale))]
    public partial class strAktivitasSale
    {
        public int AktivitasSalesID { get; set; }
        public int trMembershipID { get; set; }
        public int SalesActionID { get; set; }
        public int MemberStateID { get; set; }
        public string Note { get; set; }
        public System.DateTime? date { get; set; }
        public byte[] aktivitasstap { get; set; }

        public virtual tMemberState tMemberState { get; set; }
        public virtual trMembership trMembership { get; set; }
        public virtual tSalesAction tSalesAction { get; set; }

        public strAktivitasSale()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
