// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationStrActionKlaim))]
    public partial class StrActionKlaim
    {
        public int strActionClaimID { get; set; }
        public int ClaimID { get; set; }
        public int ActionPTID { get; set; }

        public virtual System.Collections.Generic.ICollection<StrActionKlaimParam> StrActionKlaimParams { get; set; }

        public virtual tActionPT tActionPT { get; set; }

        public StrActionKlaim()
        {
            StrActionKlaimParams = new System.Collections.Generic.List<StrActionKlaimParam>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
