// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationstrKlaimPT))]
    public partial class strKlaimPT
    {
        public int ClaimPTID { get; set; }
        public int trPersonalTrainerID { get; set; }
        public System.DateTime AwalClaim { get; set; }
        public System.DateTime AkhirClaim { get; set; }
        public bool Void { get; set; }
        public string verifikasiMember { get; set; }
        public string verifikasiPT { get; set; }
        public int AktifitasMemberID { get; set; }
        public int Kepuasan { get; set; }
        public string Note { get; set; }
        public int Jam { get; set; }

        public virtual trAktifitasMember trAktifitasMember { get; set; }
        public virtual trPersonalTrainer trPersonalTrainer { get; set; }

        public strKlaimPT()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
