// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationstrLocBO))]
    public partial class strLocBO
    {
        public int LocBoID { get; set; }
        public int PersonBOID { get; set; }
        public int LocationID { get; set; }

        public virtual System.Collections.Generic.ICollection<trCinCout> trCinCouts { get; set; }

        public virtual tLocFitnessCenter tLocFitnessCenter { get; set; }
        public virtual tUserBackOffice tUserBackOffice { get; set; }

        public strLocBO()
        {
            trCinCouts = new System.Collections.Generic.List<trCinCout>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
