// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationstrPaymentMember))]
    public partial class strPaymentMember
    {
        public int trPaymentID { get; set; }
        public int? trMembershipID { get; set; }
        public int pembayaranke { get; set; }
        public bool statusBayar { get; set; }
        public System.DateTime Tanggal { get; set; }
        public byte[] TimeStamp { get; set; }
        public int? MemberTypeID { get; set; }
        public string Note { get; set; }
        public int? MembershipDTLID { get; set; }

        public virtual System.Collections.Generic.ICollection<strPayment> strPayments { get; set; }

        public virtual tMemberType tMemberType { get; set; }
        public virtual trMembership trMembership_MembershipDTLID { get; set; }
        public virtual trMembership trMembership_trMembershipID { get; set; }

        public strPaymentMember()
        {
            strPayments = new System.Collections.Generic.List<strPayment>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
