// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationstrPersonEvent))]
    public partial class strPersonEvent
    {
        public int PersonEventId { get; set; }
        public string Gym { get; set; }
        public int NoPeserta { get; set; }

        public virtual trPersonEvent trPersonEvent { get; set; }

        public strPersonEvent()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
