// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationstrPayment))]
    public partial class strPayment
    {
        public int StrPaymentID { get; set; }
        public int PaymentWithID { get; set; }
        public int trPaymentID { get; set; }

        public virtual strPaymentMember strPaymentMember { get; set; }
        public virtual trPaymentWith trPaymentWith { get; set; }

        public strPayment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
