// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtActionPT))]
    public partial class tActionPT
    {
        public int ActionPTID { get; set; }
        public string ActionPTName { get; set; }
        public string ActionPTKet { get; set; }

        public virtual System.Collections.Generic.ICollection<StrActionKlaim> StrActionKlaims { get; set; }
        public virtual System.Collections.Generic.ICollection<trAktifitasMember> trAktifitasMembers { get; set; }

        public tActionPT()
        {
            StrActionKlaims = new System.Collections.Generic.List<StrActionKlaim>();
            trAktifitasMembers = new System.Collections.Generic.List<trAktifitasMember>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
