// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtBank))]
    public partial class tBank
    {
        public int BankID { get; set; }
        public string NamaBank { get; set; }
        public bool EDC { get; set; }

        public virtual System.Collections.Generic.ICollection<trPaymentWith> trPaymentWiths_BankID { get; set; }
        public virtual System.Collections.Generic.ICollection<trPaymentWith> trPaymentWiths_EDCID { get; set; }

        public tBank()
        {
            EDC = false;
            trPaymentWiths_BankID = new System.Collections.Generic.List<trPaymentWith>();
            trPaymentWiths_EDCID = new System.Collections.Generic.List<trPaymentWith>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
