// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtCardStatu))]
    public partial class tCardStatu
    {
        public int CardStatusID { get; set; }
        public string CardStatus { get; set; }
        public string CardDesc { get; set; }
        public bool FinalStatus { get; set; }

        public virtual System.Collections.Generic.ICollection<trMembership> trMemberships { get; set; }

        public tCardStatu()
        {
            trMemberships = new System.Collections.Generic.List<trMembership>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
