// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtEventStep))]
    public partial class tEventStep
    {
        public int EvStepId { get; set; }
        public int EvId { get; set; }
        public int Step { get; set; }
        public int PersonCount { get; set; }
        public string StepDetail { get; set; }

        public virtual System.Collections.Generic.ICollection<tEventScore> tEventScores { get; set; }
        public virtual System.Collections.Generic.ICollection<trEventStep> trEventSteps { get; set; }

        public virtual tEvent tEvent { get; set; }

        public tEventStep()
        {
            PersonCount = 0;
            tEventScores = new System.Collections.Generic.List<tEventScore>();
            trEventSteps = new System.Collections.Generic.List<trEventStep>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
