// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtEvent))]
    public partial class tEvent
    {
        public int EvId { get; set; }
        public System.DateTime EvStartDate { get; set; }
        public System.DateTime EvEndDate { get; set; }
        public string EvName { get; set; }
        public int JumlahPesertaAwal { get; set; }
        public int JumlahStep { get; set; }

        public virtual System.Collections.Generic.ICollection<tEventStep> tEventSteps { get; set; }
        public virtual System.Collections.Generic.ICollection<trPersonEvent> trPersonEvents { get; set; }

        public tEvent()
        {
            tEventSteps = new System.Collections.Generic.List<tEventStep>();
            trPersonEvents = new System.Collections.Generic.List<trPersonEvent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
