// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtKela))]
    public partial class tKela
    {
        public int KelasID { get; set; }
        public int? RuangKelasID { get; set; }
        public string KNamaKelas { get; set; }
        public byte[] ImageKelas { get; set; }

        public virtual System.Collections.Generic.ICollection<trPlanKela> trPlanKelas { get; set; }

        public virtual tRuangKela tRuangKela { get; set; }

        public tKela()
        {
            trPlanKelas = new System.Collections.Generic.List<trPlanKela>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
