// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtMemberType))]
    public partial class tMemberType
    {
        public int MemberTypeID { get; set; }
        public string MemberType { get; set; }
        public decimal Biaya { get; set; }
        public int JmlBulan { get; set; }
        public bool IsPaket { get; set; }
        public int Share { get; set; }
        public int? ShareMin { get; set; }
        public string Periode { get; set; }
        public int? LocationID { get; set; }
        public string prFix { get; set; }
        public decimal? Admin { get; set; }
        public decimal? Prorate { get; set; }
        public bool Status { get; set; }
        public int? tPaketPersonalTrainerID { get; set; }

        public virtual System.Collections.Generic.ICollection<strPaymentMember> strPaymentMembers { get; set; }
        public virtual System.Collections.Generic.ICollection<tMember> tMembers { get; set; }

        public virtual tLocFitnessCenter tLocFitnessCenter { get; set; }
        public virtual tPaketPT tPaketPT { get; set; }

        public tMemberType()
        {
            ShareMin = 0;
            prFix = "";
            Admin = 0m;
            Prorate = 0m;
            Status = true;
            strPaymentMembers = new System.Collections.Generic.List<strPaymentMember>();
            tMembers = new System.Collections.Generic.List<tMember>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
