// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtMemberState))]
    public partial class tMemberState
    {
        public int MemberStateID { get; set; }
        public string MemberStateName { get; set; }
        public string Note { get; set; }

        public virtual System.Collections.Generic.ICollection<strAktivitasSale> strAktivitasSales { get; set; }

        public tMemberState()
        {
            strAktivitasSales = new System.Collections.Generic.List<strAktivitasSale>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
