// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtPaketPT))]
    public partial class tPaketPT
    {
        public int tPaketPTID { get; set; }
        public string PPTNama { get; set; }
        public int PPTJam { get; set; }
        public int PPTPersonTotal { get; set; }
        public decimal? PPTHarga { get; set; }
        public int? PPTMasa { get; set; }
        public bool PPTStatus { get; set; }
        public string PPTDesc { get; set; }
        public bool PPTMembership { get; set; }

        public virtual System.Collections.Generic.ICollection<tMemberType> tMemberTypes { get; set; }
        public virtual System.Collections.Generic.ICollection<trPersonalTrainer> trPersonalTrainers { get; set; }

        public tPaketPT()
        {
            PPTStatus = true;
            tMemberTypes = new System.Collections.Generic.List<tMemberType>();
            trPersonalTrainers = new System.Collections.Generic.List<trPersonalTrainer>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
