// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtPaymentType))]
    public partial class tPaymentType
    {
        public int PaymentTypeID { get; set; }
        public string NamaType { get; set; }

        public virtual System.Collections.Generic.ICollection<trPaymentWith> trPaymentWiths { get; set; }

        public tPaymentType()
        {
            trPaymentWiths = new System.Collections.Generic.List<trPaymentWith>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
