// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtPerson))]
    public partial class tPerson
    {
        public int PersonID { get; set; }
        public string PNama { get; set; }
        public string PTempLahir { get; set; }
        public System.DateTime? PTglLahir { get; set; }
        public string PGender { get; set; }
        public string PAlamat { get; set; }
        public string PRT { get; set; }
        public string PRW { get; set; }
        public string PKelurahan { get; set; }
        public string PKecamatan { get; set; }
        public string PKota { get; set; }
        public string PPropinsi { get; set; }
        public string PIdentitas { get; set; }
        public string PEmail { get; set; }
        public string PTelp { get; set; }
        public string PHP1 { get; set; }
        public string PHP2 { get; set; }
        public string PPinBB { get; set; }
        public string Id { get; set; }

        public virtual System.Collections.Generic.ICollection<stMemberFingerPrint> stMemberFingerPrints { get; set; }
        public virtual System.Collections.Generic.ICollection<tMember> tMembers { get; set; }
        public virtual System.Collections.Generic.ICollection<trPersonEvent> trPersonEvents { get; set; }
        public virtual System.Collections.Generic.ICollection<trTTD> trTTDs { get; set; }
        public virtual tUserBackOffice tUserBackOffice { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }

        public tPerson()
        {
            stMemberFingerPrints = new System.Collections.Generic.List<stMemberFingerPrint>();
            tMembers = new System.Collections.Generic.List<tMember>();
            trPersonEvents = new System.Collections.Generic.List<trPersonEvent>();
            trTTDs = new System.Collections.Generic.List<trTTD>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
