// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtPosisi))]
    public partial class tPosisi
    {
        public int PosisiID { get; set; }
        public string PNamaPosisi { get; set; }

        public virtual System.Collections.Generic.ICollection<tUserBackOffice> tUserBackOffices { get; set; }

        public tPosisi()
        {
            tUserBackOffices = new System.Collections.Generic.List<tUserBackOffice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
