// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrAktifitasKela))]
    public partial class trAktifitasKela
    {
        public int AktifitasKelasID { get; set; }
        public int PlanKelasID { get; set; }
        public int? AktifitasMemberID { get; set; }

        public virtual trAktifitasMember trAktifitasMember { get; set; }
        public virtual trPlanKela trPlanKela { get; set; }

        public trAktifitasKela()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
