// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrCinCout))]
    public partial class trCinCout
    {
        public int CinCoutID { get; set; }
        public byte[] RefCinCout { get; set; }
        public int PersonBOID { get; set; }
        public System.DateTime TimeStatus { get; set; }
        public int TypeStatusInOut { get; set; }
        public int LocBoID { get; set; }

        public virtual strLocBO strLocBO { get; set; }
        public virtual tTypeStatusCinCout tTypeStatusCinCout { get; set; }
        public virtual tUserBackOffice tUserBackOffice { get; set; }

        public trCinCout()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
