// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrEventScore))]
    public partial class trEventScore
    {
        public int trEvScoreId { get; set; }
        public int? trEventStepId { get; set; }
        public int? PersonEventId { get; set; }
        public int? EvScoreId { get; set; }
        public int? Score { get; set; }

        public virtual tEventScore tEventScore { get; set; }
        public virtual trEventStep trEventStep { get; set; }
        public virtual trPersonEvent trPersonEvent { get; set; }

        public trEventScore()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
