// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrMembership))]
    public partial class trMembership
    {
        public int trMembershipID { get; set; }
        public int? ParentID { get; set; }
        public int LocationID { get; set; }
        public byte[] MSTime { get; set; }
        public System.DateTime MSTglMulai { get; set; }
        public System.DateTime MSTglSelesai { get; set; }
        public int PersonBOIDADM { get; set; }
        public int PersonBOIDSales { get; set; }
        public int StatusMID { get; set; }
        public decimal? Subtotal { get; set; }
        public decimal? Disc { get; set; }
        public decimal? Total { get; set; }
        public int? GenBayar { get; set; }
        public string Note { get; set; }
        public int MemberID { get; set; }
        public string AgreementID { get; set; }
        public int CountMember { get; set; }
        public int seq { get; set; }
        public decimal? Admin { get; set; }
        public decimal? Prorate { get; set; }
        public int CardStatus { get; set; }
        public int TotalMonth { get; set; }
        public string AccountingStatus { get; set; }
        public string ActivationCode { get; set; }
        public System.DateTime? MSInput { get; set; }
        public string DiscType { get; set; }
        public decimal? DiscVal { get; set; }

        public virtual System.Collections.Generic.ICollection<strAktivitasSale> strAktivitasSales { get; set; }
        public virtual System.Collections.Generic.ICollection<strPaymentMember> strPaymentMembers_MembershipDTLID { get; set; }
        public virtual System.Collections.Generic.ICollection<strPaymentMember> strPaymentMembers_trMembershipID { get; set; }
        public virtual System.Collections.Generic.ICollection<trMembership> trMemberships { get; set; }
        public virtual System.Collections.Generic.ICollection<trPersonalTrainer> trPersonalTrainers { get; set; }
        public virtual System.Collections.Generic.ICollection<trTTD> trTTDs { get; set; }

        public virtual tCardStatu tCardStatu { get; set; }
        public virtual tLocFitnessCenter tLocFitnessCenter { get; set; }
        public virtual tMember tMember { get; set; }
        public virtual trMembership trMembership_ParentID { get; set; }
        public virtual tStatusMember tStatusMember { get; set; }
        public virtual tUserBackOffice tUserBackOffice_PersonBOIDADM { get; set; }
        public virtual tUserBackOffice tUserBackOffice_PersonBOIDSales { get; set; }

        public trMembership()
        {
            CountMember = 1;
            seq = 0;
            Admin = 0m;
            Prorate = 0m;
            strAktivitasSales = new System.Collections.Generic.List<strAktivitasSale>();
            strPaymentMembers_MembershipDTLID = new System.Collections.Generic.List<strPaymentMember>();
            strPaymentMembers_trMembershipID = new System.Collections.Generic.List<strPaymentMember>();
            trMemberships = new System.Collections.Generic.List<trMembership>();
            trPersonalTrainers = new System.Collections.Generic.List<trPersonalTrainer>();
            trTTDs = new System.Collections.Generic.List<trTTD>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
