// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtRoleEvent))]
    public partial class tRoleEvent
    {
        public int EvRoleId { get; set; }
        public string EvRoleName { get; set; }

        public virtual System.Collections.Generic.ICollection<trPersonEvent> trPersonEvents { get; set; }

        public tRoleEvent()
        {
            trPersonEvents = new System.Collections.Generic.List<trPersonEvent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
