// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrPersonalTrainer))]
    public partial class trPersonalTrainer
    {
        public int trPersonalTrainerID { get; set; }
        public int tPaketPTID { get; set; }
        public int? SisaJam { get; set; }
        public int? PersonBOIDPT { get; set; }
        public int seq { get; set; }
        public int? ParentID { get; set; }
        public int? Masa { get; set; }
        public int? trMembershipID { get; set; }

        public virtual System.Collections.Generic.ICollection<strKlaimPT> strKlaimPTs { get; set; }
        public virtual System.Collections.Generic.ICollection<trPersonalTrainer> trPersonalTrainers { get; set; }
        public virtual System.Collections.Generic.ICollection<trPlanAktifitasPT> trPlanAktifitasPTs { get; set; }
        public virtual System.Collections.Generic.ICollection<trTTD> trTTDs { get; set; }

        public virtual tPaketPT tPaketPT { get; set; }
        public virtual trMembership trMembership { get; set; }
        public virtual trPersonalTrainer trPersonalTrainer_ParentID { get; set; }
        public virtual tUserBackOffice tUserBackOffice { get; set; }

        public trPersonalTrainer()
        {
            strKlaimPTs = new System.Collections.Generic.List<strKlaimPT>();
            trPersonalTrainers = new System.Collections.Generic.List<trPersonalTrainer>();
            trPlanAktifitasPTs = new System.Collections.Generic.List<trPlanAktifitasPT>();
            trTTDs = new System.Collections.Generic.List<trTTD>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
