// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrPersonEvent))]
    public partial class trPersonEvent
    {
        public int PersonEventId { get; set; }
        public int PersonId { get; set; }
        public int EvId { get; set; }
        public int EvRoleId { get; set; }

        public virtual strPersonEvent strPersonEvent { get; set; }
        public virtual System.Collections.Generic.ICollection<trEventScore> trEventScores { get; set; }
        public virtual System.Collections.Generic.ICollection<trEventStep> trEventSteps { get; set; }

        public virtual tEvent tEvent { get; set; }
        public virtual tPerson tPerson { get; set; }
        public virtual tRoleEvent tRoleEvent { get; set; }

        public trPersonEvent()
        {
            trEventScores = new System.Collections.Generic.List<trEventScore>();
            trEventSteps = new System.Collections.Generic.List<trEventStep>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
