// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrPlanAktifitasPT))]
    public partial class trPlanAktifitasPT
    {
        public int PlanAktifitasPTID { get; set; }
        public int PersonalTrainerID { get; set; }
        public int? PalnAktifitasPTParentID { get; set; }
        public int DayOfWeek { get; set; }
        public string period { get; set; }
        public System.TimeSpan WaktuMulai { get; set; }
        public System.TimeSpan WaktuSelesai { get; set; }
        public int LocationID { get; set; }
        public int MemberID { get; set; }
        public int PersonBOIDPT { get; set; }
        public int PersonBOID { get; set; }
        public string Note { get; set; }

        public virtual System.Collections.Generic.ICollection<trPlanAktifitasPT> trPlanAktifitasPTs { get; set; }

        public virtual tLocFitnessCenter tLocFitnessCenter { get; set; }
        public virtual tMember tMember { get; set; }
        public virtual trPersonalTrainer trPersonalTrainer { get; set; }
        public virtual trPlanAktifitasPT trPlanAktifitasPT_PalnAktifitasPTParentID { get; set; }
        public virtual tUserBackOffice tUserBackOffice_PersonBOID { get; set; }
        public virtual tUserBackOffice tUserBackOffice_PersonBOIDPT { get; set; }

        public trPlanAktifitasPT()
        {
            trPlanAktifitasPTs = new System.Collections.Generic.List<trPlanAktifitasPT>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
