// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtrTTD))]
    public partial class trTTD
    {
        public int TrTTDID { get; set; }
        public int? trMembershipID { get; set; }
        public int? trPTID { get; set; }
        public byte[] trTTD_ { get; set; }
        public int MemberID { get; set; }

        public virtual tMember tMember { get; set; }
        public virtual tPerson tPerson { get; set; }
        public virtual trMembership trMembership { get; set; }
        public virtual trPersonalTrainer trPersonalTrainer { get; set; }

        public trTTD()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
