// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtRuangKela))]
    public partial class tRuangKela
    {
        public int RuangKelasID { get; set; }
        public string NRuangKelas { get; set; }
        public string BackGround { get; set; }
        public string Map { get; set; }
        public int? Kapasitas { get; set; }

        public virtual System.Collections.Generic.ICollection<tKela> tKelas { get; set; }

        public tRuangKela()
        {
            tKelas = new System.Collections.Generic.List<tKela>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
