// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Entities
{
	using System.ComponentModel.DataAnnotations;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
	[MetadataType(typeof(DataValidator.Validation.ValidationtUserBackOffice))]
    public partial class tUserBackOffice
    {
        public int PersonBOID { get; set; }
        public string BOIDNO { get; set; }
        public bool StatusBOID { get; set; }
        public System.DateTime BMulai { get; set; }
        public byte[] BFoto { get; set; }
        public byte[] BFotoKTP { get; set; }
        public byte[] BFotoSignature { get; set; }
        public string BRFID { get; set; }
        public int PosisiID { get; set; }
        public string Background { get; set; }

        public virtual System.Collections.Generic.ICollection<strLocBO> strLocBOes { get; set; }
        public virtual System.Collections.Generic.ICollection<trAktifitasMember> trAktifitasMembers { get; set; }
        public virtual System.Collections.Generic.ICollection<trCinCout> trCinCouts { get; set; }
        public virtual System.Collections.Generic.ICollection<trMembership> trMemberships_PersonBOIDADM { get; set; }
        public virtual System.Collections.Generic.ICollection<trMembership> trMemberships_PersonBOIDSales { get; set; }
        public virtual System.Collections.Generic.ICollection<trPembayaran> trPembayarans { get; set; }
        public virtual System.Collections.Generic.ICollection<trPersonalTrainer> trPersonalTrainers { get; set; }
        public virtual System.Collections.Generic.ICollection<trPlanAktifitasPT> trPlanAktifitasPTs_PersonBOID { get; set; }
        public virtual System.Collections.Generic.ICollection<trPlanAktifitasPT> trPlanAktifitasPTs_PersonBOIDPT { get; set; }
        public virtual System.Collections.Generic.ICollection<trPlanKela> trPlanKelas_PersonBOIDAdm { get; set; }
        public virtual System.Collections.Generic.ICollection<trPlanKela> trPlanKelas_PersonBOIDInstruktur { get; set; }

        public virtual tPerson tPerson { get; set; }
        public virtual tPosisi tPosisi { get; set; }

        public tUserBackOffice()
        {
            strLocBOes = new System.Collections.Generic.List<strLocBO>();
            trAktifitasMembers = new System.Collections.Generic.List<trAktifitasMember>();
            trCinCouts = new System.Collections.Generic.List<trCinCout>();
            trMemberships_PersonBOIDADM = new System.Collections.Generic.List<trMembership>();
            trMemberships_PersonBOIDSales = new System.Collections.Generic.List<trMembership>();
            trPembayarans = new System.Collections.Generic.List<trPembayaran>();
            trPersonalTrainers = new System.Collections.Generic.List<trPersonalTrainer>();
            trPlanAktifitasPTs_PersonBOID = new System.Collections.Generic.List<trPlanAktifitasPT>();
            trPlanAktifitasPTs_PersonBOIDPT = new System.Collections.Generic.List<trPlanAktifitasPT>();
            trPlanKelas_PersonBOIDAdm = new System.Collections.Generic.List<trPlanKela>();
            trPlanKelas_PersonBOIDInstruktur = new System.Collections.Generic.List<trPlanKela>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
