// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ApplicationUserGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApplicationUserGroup>
    {
        public ApplicationUserGroupConfiguration()
            : this("dbo")
        {
        }

        public ApplicationUserGroupConfiguration(string schema)
        {
            ToTable(schema + ".ApplicationUserGroups");
            HasKey(x => new { x.ApplicationUserId, x.ApplicationGroupId });

            Property(x => x.ApplicationUserId).HasColumnName(@"ApplicationUserId").IsRequired().HasColumnType("nvarchar").HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ApplicationGroupId).HasColumnName(@"ApplicationGroupId").IsRequired().HasColumnType("nvarchar").HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            HasRequired(a => a.ApplicationGroup).WithMany(b => b.ApplicationUserGroups).HasForeignKey(c => c.ApplicationGroupId).WillCascadeOnDelete();
        }
    }

}
// </auto-generated>
