// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class AspFormAuthorizationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AspFormAuthorization>
    {
        public AspFormAuthorizationConfiguration()
            : this("dbo")
        {
        }

        public AspFormAuthorizationConfiguration(string schema)
        {
            ToTable(schema + ".AspFormAuthorization");
            HasKey(x => x.authID);

            Property(x => x.authID).HasColumnName(@"authID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FormID).HasColumnName(@"FormID").IsRequired().HasColumnType("int");
            Property(x => x.GroupId).HasColumnName(@"GroupId").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);

            HasRequired(a => a.ApplicationGroup).WithMany(b => b.AspFormAuthorizations).HasForeignKey(c => c.GroupId);
            HasRequired(a => a.AspForm).WithMany(b => b.AspFormAuthorizations).HasForeignKey(c => c.FormID);
        }
    }

}
// </auto-generated>
