// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class AspFormConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AspForm>
    {
        public AspFormConfiguration()
            : this("dbo")
        {
        }

        public AspFormConfiguration(string schema)
        {
            ToTable(schema + ".AspForm");
            HasKey(x => x.FormId);

            Property(x => x.FormId).HasColumnName(@"FormId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.parent_ID).HasColumnName(@"parent_ID").IsOptional().HasColumnType("int");
            Property(x => x.MasterModule).HasColumnName(@"MasterModule").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
            Property(x => x.Module).HasColumnName(@"Module").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
            Property(x => x.title).HasColumnName(@"title").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(150);
            Property(x => x.desciption).HasColumnName(@"desciption").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.controller).HasColumnName(@"controller").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.action).HasColumnName(@"action").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.url).HasColumnName(@"url").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.area).HasColumnName(@"area").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.visible).HasColumnName(@"visible").IsOptional().HasColumnType("bit");
            Property(x => x.parameter).HasColumnName(@"parameter").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.clickable).HasColumnName(@"clickable").IsOptional().HasColumnType("bit");
            Property(x => x.statusCode).HasColumnName(@"statusCode").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(10);
            Property(x => x.displayOrder).HasColumnName(@"displayOrder").IsOptional().HasColumnType("int");
            Property(x => x.iconclass).HasColumnName(@"iconclass").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Parent).HasColumnName(@"Parent").IsOptional().HasColumnType("bit");

            HasOptional(a => a.AspForm_parent_ID).WithMany(b => b.AspForms).HasForeignKey(c => c.parent_ID);
        }
    }

}
// </auto-generated>
