// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ExcelUploadDBConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ExcelUploadDB>
    {
        public ExcelUploadDBConfiguration()
            : this("dbo")
        {
        }

        public ExcelUploadDBConfiguration(string schema)
        {
            ToTable(schema + ".ExcelUploadDB");
            HasKey(x => x.No);

            Property(x => x.No).HasColumnName(@"No").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Date).HasColumnName(@"Date").IsOptional().HasColumnType("date");
            Property(x => x.Agreement).HasColumnName(@"Agreement").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
            Property(x => x.AgreementFix).HasColumnName(@"AgreementFix").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.MemberName).HasColumnName(@"MemberName").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").IsOptional().HasColumnType("date");
            Property(x => x.Telp).HasColumnName(@"Telp").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.MembershipType).HasColumnName(@"MembershipType").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.MembershipTypeFix).HasColumnName(@"MembershipTypeFix").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.RecordType).HasColumnName(@"RecordType").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.LongTime).HasColumnName(@"LongTime").IsOptional().HasColumnType("int");
            Property(x => x.EFD).HasColumnName(@"EFD").IsOptional().HasColumnType("date");
            Property(x => x.EXP).HasColumnName(@"EXP").IsOptional().HasColumnType("datetime");
            Property(x => x.Paid1).HasColumnName(@"Paid1").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Paid2).HasColumnName(@"Paid2").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Paid3).HasColumnName(@"Paid3").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.MBR1).HasColumnName(@"MBR1").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.MBR2).HasColumnName(@"MBR2").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.By1).HasColumnName(@"By1").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.By2).HasColumnName(@"By2").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Sold).HasColumnName(@"Sold").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Remarks).HasColumnName(@"Remarks").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.Address).HasColumnName(@"Address").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.GymBag).HasColumnName(@"GymBag").IsOptional().HasColumnType("bit");
            Property(x => x.Tshirt).HasColumnName(@"Tshirt").IsOptional().HasColumnType("bit");
            Property(x => x.Bank).HasColumnName(@"Bank").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Payment).HasColumnName(@"Payment").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Updated).HasColumnName(@"Updated").IsOptional().HasColumnType("bit");
            Property(x => x.prfix).HasColumnName(@"prfix").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(1);
        }
    }

}
// </auto-generated>
