// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class ExcelPTConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ExcelPT>
    {
        public ExcelPTConfiguration()
            : this("dbo")
        {
        }

        public ExcelPTConfiguration(string schema)
        {
            ToTable(schema + ".ExcelPT");
            HasKey(x => x.No);

            Property(x => x.No).HasColumnName(@"No").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Date).HasColumnName(@"Date").IsOptional().HasColumnType("datetime");
            Property(x => x.Aggrement).HasColumnName(@"Aggrement").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Nama).HasColumnName(@"Nama").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.DOB).HasColumnName(@"DOB").IsOptional().HasColumnType("datetime");
            Property(x => x.Telp).HasColumnName(@"Telp").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Type).HasColumnName(@"Type").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.LongTime).HasColumnName(@"LongTime").IsOptional().HasColumnType("int");
            Property(x => x.EFD).HasColumnName(@"EFD").IsOptional().HasColumnType("datetime");
            Property(x => x.EXP).HasColumnName(@"EXP").IsOptional().HasColumnType("datetime");
            Property(x => x.Paid).HasColumnName(@"Paid").IsOptional().HasColumnType("decimal");
            Property(x => x.Paid2).HasColumnName(@"Paid2").IsOptional().HasColumnType("decimal");
            Property(x => x.By1).HasColumnName(@"By1").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.By2).HasColumnName(@"By2").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Remark).HasColumnName(@"Remark").IsOptional().HasColumnType("nvarchar").HasMaxLength(1000);
            Property(x => x.Address).HasColumnName(@"Address").IsOptional().HasColumnType("nvarchar").HasMaxLength(1000);
        }
    }

}
// </auto-generated>
