// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class logConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<log>
    {
        public logConfiguration()
            : this("dbo")
        {
        }

        public logConfiguration(string schema)
        {
            ToTable(schema + ".log");
            HasKey(x => x.id);

            Property(x => x.id).HasColumnName(@"id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.date).HasColumnName(@"date").IsOptional().HasColumnType("datetime");
            Property(x => x.identity).HasColumnName(@"identity").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.level).HasColumnName(@"level").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.logger).HasColumnName(@"logger").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.message).HasColumnName(@"message").IsOptional().IsUnicode(false).HasColumnType("varchar");
            Property(x => x.timestamp).HasColumnName(@"timestamp").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(10);
            Property(x => x.type).HasColumnName(@"type").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.username).HasColumnName(@"username").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.utcdate).HasColumnName(@"utcdate").IsOptional().HasColumnType("datetime");
            Property(x => x.IdTable).HasColumnName(@"IdTable").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.NamaTransaksi).HasColumnName(@"NamaTransaksi").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.NamaTable).HasColumnName(@"NamaTable").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.exception).HasColumnName(@"exception").IsOptional().IsUnicode(false).HasColumnType("varchar");
        }
    }

}
// </auto-generated>
