// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class LogtestConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Logtest>
    {
        public LogtestConfiguration()
            : this("dbo")
        {
        }

        public LogtestConfiguration(string schema)
        {
            ToTable(schema + ".Logtest");
            HasKey(x => new { x.Id, x.Date, x.Thread, x.Level, x.Logger, x.Message });

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Date).HasColumnName(@"Date").IsRequired().HasColumnType("datetime");
            Property(x => x.Thread).HasColumnName(@"Thread").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.Level).HasColumnName(@"Level").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Logger).HasColumnName(@"Logger").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(255);
            Property(x => x.Message).HasColumnName(@"Message").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(4000);
            Property(x => x.Exception).HasColumnName(@"Exception").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(2000);
        }
    }

}
// </auto-generated>
