// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class stMemberFingerPrintConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<stMemberFingerPrint>
    {
        public stMemberFingerPrintConfiguration()
            : this("dbo")
        {
        }

        public stMemberFingerPrintConfiguration(string schema)
        {
            ToTable(schema + ".stMemberFingerPrint");
            HasKey(x => x.stMemberFingerprintId);

            Property(x => x.stMemberFingerprintId).HasColumnName(@"stMemberFingerprintId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonId).HasColumnName(@"PersonId").IsOptional().HasColumnType("int");
            Property(x => x.seq).HasColumnName(@"seq").IsOptional().HasColumnType("smallint");
            Property(x => x.note).HasColumnName(@"note").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.pict).HasColumnName(@"pict").IsOptional().HasColumnType("image").HasMaxLength(2147483647);

            HasOptional(a => a.tPerson).WithMany(b => b.stMemberFingerPrints).HasForeignKey(c => c.PersonId);
        }
    }

}
// </auto-generated>
