// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class StrActionKlaimParamConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StrActionKlaimParam>
    {
        public StrActionKlaimParamConfiguration()
            : this("dbo")
        {
        }

        public StrActionKlaimParamConfiguration(string schema)
        {
            ToTable(schema + ".StrActionKlaimParam");
            HasKey(x => x.IdPar);

            Property(x => x.IdPar).HasColumnName(@"IdPar").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StrActionClaimId).HasColumnName(@"StrActionClaimId").IsRequired().HasColumnType("int");
            Property(x => x.NamaParam).HasColumnName(@"NamaParam").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Satuan).HasColumnName(@"Satuan").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(10);
            Property(x => x.Value).HasColumnName(@"Value").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);

            HasRequired(a => a.StrActionKlaim).WithMany(b => b.StrActionKlaimParams).HasForeignKey(c => c.StrActionClaimId);
        }
    }

}
// </auto-generated>
