// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class strKlaimPTConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<strKlaimPT>
    {
        public strKlaimPTConfiguration()
            : this("dbo")
        {
        }

        public strKlaimPTConfiguration(string schema)
        {
            ToTable(schema + ".strKlaimPT");
            HasKey(x => x.ClaimPTID);

            Property(x => x.ClaimPTID).HasColumnName(@"ClaimPTID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.trPersonalTrainerID).HasColumnName(@"trPersonalTrainerID").IsRequired().HasColumnType("int");
            Property(x => x.AwalClaim).HasColumnName(@"AwalClaim").IsRequired().HasColumnType("datetime");
            Property(x => x.AkhirClaim).HasColumnName(@"AkhirClaim").IsRequired().HasColumnType("datetime");
            Property(x => x.Void).HasColumnName(@"Void").IsRequired().HasColumnType("bit");
            Property(x => x.verifikasiMember).HasColumnName(@"verifikasiMember").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.verifikasiPT).HasColumnName(@"verifikasiPT").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.AktifitasMemberID).HasColumnName(@"AktifitasMemberID").IsRequired().HasColumnType("int");
            Property(x => x.Kepuasan).HasColumnName(@"Kepuasan").IsRequired().HasColumnType("int");
            Property(x => x.Note).HasColumnName(@"Note").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Jam).HasColumnName(@"Jam").IsRequired().HasColumnType("int");

            HasRequired(a => a.trAktifitasMember).WithMany(b => b.strKlaimPTs).HasForeignKey(c => c.AktifitasMemberID);
            HasRequired(a => a.trPersonalTrainer).WithMany(b => b.strKlaimPTs).HasForeignKey(c => c.trPersonalTrainerID);
        }
    }

}
// </auto-generated>
