// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class strLocBOConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<strLocBO>
    {
        public strLocBOConfiguration()
            : this("dbo")
        {
        }

        public strLocBOConfiguration(string schema)
        {
            ToTable(schema + ".strLocBO");
            HasKey(x => x.LocBoID);

            Property(x => x.LocBoID).HasColumnName(@"LocBoID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonBOID).HasColumnName(@"PersonBOID").IsRequired().HasColumnType("int");
            Property(x => x.LocationID).HasColumnName(@"LocationID").IsRequired().HasColumnType("int");

            HasRequired(a => a.tLocFitnessCenter).WithMany(b => b.strLocBOes).HasForeignKey(c => c.LocationID);
            HasRequired(a => a.tUserBackOffice).WithMany(b => b.strLocBOes).HasForeignKey(c => c.PersonBOID);
        }
    }

}
// </auto-generated>
