// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class strPersonEventConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<strPersonEvent>
    {
        public strPersonEventConfiguration()
            : this("dbo")
        {
        }

        public strPersonEventConfiguration(string schema)
        {
            ToTable(schema + ".strPersonEvent");
            HasKey(x => x.PersonEventId);

            Property(x => x.PersonEventId).HasColumnName(@"PersonEventId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Gym).HasColumnName(@"Gym").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.NoPeserta).HasColumnName(@"NoPeserta").IsRequired().HasColumnType("int");

            HasRequired(a => a.trPersonEvent).WithOptional(b => b.strPersonEvent);
        }
    }

}
// </auto-generated>
