// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class sysdiagramConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<sysdiagram>
    {
        public sysdiagramConfiguration()
            : this("dbo")
        {
        }

        public sysdiagramConfiguration(string schema)
        {
            ToTable(schema + ".sysdiagrams");
            HasKey(x => x.diagram_id);

            Property(x => x.name).HasColumnName(@"name").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.principal_id).HasColumnName(@"principal_id").IsRequired().HasColumnType("int");
            Property(x => x.diagram_id).HasColumnName(@"diagram_id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.version).HasColumnName(@"version").IsOptional().HasColumnType("int");
            Property(x => x.definition).HasColumnName(@"definition").IsOptional().HasColumnType("varbinary");
        }
    }

}
// </auto-generated>
