// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tCardStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tCardStatu>
    {
        public tCardStatuConfiguration()
            : this("dbo")
        {
        }

        public tCardStatuConfiguration(string schema)
        {
            ToTable(schema + ".tCardStatus");
            HasKey(x => x.CardStatusID);

            Property(x => x.CardStatusID).HasColumnName(@"CardStatusID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CardStatus).HasColumnName(@"CardStatus").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
            Property(x => x.CardDesc).HasColumnName(@"CardDesc").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.FinalStatus).HasColumnName(@"FinalStatus").IsRequired().HasColumnType("bit");
        }
    }

}
// </auto-generated>
