// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tEventScoreConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tEventScore>
    {
        public tEventScoreConfiguration()
            : this("dbo")
        {
        }

        public tEventScoreConfiguration(string schema)
        {
            ToTable(schema + ".tEventScore");
            HasKey(x => x.EvScoreId);

            Property(x => x.EvScoreId).HasColumnName(@"EvScoreId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EvScoreName).HasColumnName(@"EvScoreName").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.EvStepId).HasColumnName(@"EvStepId").IsOptional().HasColumnType("int");
            Property(x => x.MinScore).HasColumnName(@"MinScore").IsOptional().HasColumnType("int");
            Property(x => x.MaxScore).HasColumnName(@"MaxScore").IsOptional().HasColumnType("int");

            HasOptional(a => a.tEventStep).WithMany(b => b.tEventScores).HasForeignKey(c => c.EvStepId);
        }
    }

}
// </auto-generated>
