// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tEventStepConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tEventStep>
    {
        public tEventStepConfiguration()
            : this("dbo")
        {
        }

        public tEventStepConfiguration(string schema)
        {
            ToTable(schema + ".tEventStep");
            HasKey(x => x.EvStepId);

            Property(x => x.EvStepId).HasColumnName(@"EvStepId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EvId).HasColumnName(@"EvId").IsRequired().HasColumnType("int");
            Property(x => x.Step).HasColumnName(@"Step").IsRequired().HasColumnType("int");
            Property(x => x.PersonCount).HasColumnName(@"PersonCount").IsRequired().HasColumnType("int");
            Property(x => x.StepDetail).HasColumnName(@"StepDetail").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);

            HasRequired(a => a.tEvent).WithMany(b => b.tEventSteps).HasForeignKey(c => c.EvId);
        }
    }

}
// </auto-generated>
