// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tEventConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tEvent>
    {
        public tEventConfiguration()
            : this("dbo")
        {
        }

        public tEventConfiguration(string schema)
        {
            ToTable(schema + ".tEvent");
            HasKey(x => x.EvId);

            Property(x => x.EvId).HasColumnName(@"EvId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EvStartDate).HasColumnName(@"EvStartDate").IsRequired().HasColumnType("date");
            Property(x => x.EvEndDate).HasColumnName(@"EvEndDate").IsRequired().HasColumnType("date");
            Property(x => x.EvName).HasColumnName(@"EvName").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.JumlahPesertaAwal).HasColumnName(@"JumlahPesertaAwal").IsRequired().HasColumnType("int");
            Property(x => x.JumlahStep).HasColumnName(@"JumlahStep").IsRequired().HasColumnType("int");
        }
    }

}
// </auto-generated>
