// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tKelaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tKela>
    {
        public tKelaConfiguration()
            : this("dbo")
        {
        }

        public tKelaConfiguration(string schema)
        {
            ToTable(schema + ".tKelas");
            HasKey(x => x.KelasID);

            Property(x => x.KelasID).HasColumnName(@"KelasID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RuangKelasID).HasColumnName(@"RuangKelasID").IsOptional().HasColumnType("int");
            Property(x => x.KNamaKelas).HasColumnName(@"KNamaKelas").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.ImageKelas).HasColumnName(@"ImageKelas").IsOptional().HasColumnType("image").HasMaxLength(2147483647);

            HasOptional(a => a.tRuangKela).WithMany(b => b.tKelas).HasForeignKey(c => c.RuangKelasID);
        }
    }

}
// </auto-generated>
