// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tLocFitnessCenterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tLocFitnessCenter>
    {
        public tLocFitnessCenterConfiguration()
            : this("dbo")
        {
        }

        public tLocFitnessCenterConfiguration(string schema)
        {
            ToTable(schema + ".tLocFitnessCenter");
            HasKey(x => x.LocationID);

            Property(x => x.LocationID).HasColumnName(@"LocationID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.LAlamat).HasColumnName(@"LAlamat").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.LTlp).HasColumnName(@"LTlp").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.LFax).HasColumnName(@"LFax").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.LAuth).HasColumnName(@"LAuth").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.LSpatial).HasColumnName(@"LSpatial").IsOptional().HasColumnType("geography");
        }
    }

}
// </auto-generated>
