// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tMemberTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tMemberType>
    {
        public tMemberTypeConfiguration()
            : this("dbo")
        {
        }

        public tMemberTypeConfiguration(string schema)
        {
            ToTable(schema + ".tMemberType");
            HasKey(x => x.MemberTypeID);

            Property(x => x.MemberTypeID).HasColumnName(@"MemberTypeID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MemberType).HasColumnName(@"MemberType").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.Biaya).HasColumnName(@"Biaya").IsRequired().HasColumnType("decimal");
            Property(x => x.JmlBulan).HasColumnName(@"JmlBulan").IsRequired().HasColumnType("int");
            Property(x => x.IsPaket).HasColumnName(@"IsPaket").IsRequired().HasColumnType("bit");
            Property(x => x.Share).HasColumnName(@"Share").IsRequired().HasColumnType("int");
            Property(x => x.ShareMin).HasColumnName(@"ShareMin").IsOptional().HasColumnType("int");
            Property(x => x.Periode).HasColumnName(@"Periode").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(6);
            Property(x => x.LocationID).HasColumnName(@"LocationID").IsOptional().HasColumnType("int");
            Property(x => x.prFix).HasColumnName(@"prFix").IsRequired().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(1);
            Property(x => x.Admin).HasColumnName(@"Admin").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Prorate).HasColumnName(@"Prorate").IsOptional().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Status).HasColumnName(@"Status").IsRequired().HasColumnType("bit");
            Property(x => x.tPaketPersonalTrainerID).HasColumnName(@"tPaketPersonalTrainerID").IsOptional().HasColumnType("int");

            HasOptional(a => a.tLocFitnessCenter).WithMany(b => b.tMemberTypes).HasForeignKey(c => c.LocationID);
            HasOptional(a => a.tPaketPT).WithMany(b => b.tMemberTypes).HasForeignKey(c => c.tPaketPersonalTrainerID);
        }
    }

}
// </auto-generated>
