// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tMemberStateConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tMemberState>
    {
        public tMemberStateConfiguration()
            : this("dbo")
        {
        }

        public tMemberStateConfiguration(string schema)
        {
            ToTable(schema + ".tMemberState");
            HasKey(x => x.MemberStateID);

            Property(x => x.MemberStateID).HasColumnName(@"MemberStateID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MemberStateName).HasColumnName(@"MemberStateName").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Note).HasColumnName(@"Note").IsOptional().HasColumnType("nvarchar");
        }
    }

}
// </auto-generated>
