// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tMemberConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tMember>
    {
        public tMemberConfiguration()
            : this("dbo")
        {
        }

        public tMemberConfiguration(string schema)
        {
            ToTable(schema + ".tMember");
            HasKey(x => x.MemberID);

            Property(x => x.MemberID).HasColumnName(@"MemberID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MemberNO).HasColumnName(@"MemberNO").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.PersonID).HasColumnName(@"PersonID").IsRequired().HasColumnType("int");
            Property(x => x.MRFID).HasColumnName(@"MRFID").IsOptional().HasColumnType("nvarchar");
            Property(x => x.MFotoSignature).HasColumnName(@"MFotoSignature").IsOptional().IsUnicode(false).HasColumnType("text").HasMaxLength(2147483647);
            Property(x => x.MFoto).HasColumnName(@"MFoto").IsOptional().IsUnicode(false).HasColumnType("text").HasMaxLength(2147483647);
            Property(x => x.MFotoKTP).HasColumnName(@"MFotoKTP").IsOptional().IsUnicode(false).HasColumnType("text").HasMaxLength(2147483647);
            Property(x => x.MFotoCCDebit).HasColumnName(@"MFotoCCDebit").IsOptional().IsUnicode(false).HasColumnType("text").HasMaxLength(2147483647);
            Property(x => x.MemberTypeID).HasColumnName(@"MemberTypeID").IsOptional().HasColumnType("int");
            Property(x => x.MFotoUrl).HasColumnName(@"MFotoUrl").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);

            HasOptional(a => a.tMemberType).WithMany(b => b.tMembers).HasForeignKey(c => c.MemberTypeID);
            HasRequired(a => a.tPerson).WithMany(b => b.tMembers).HasForeignKey(c => c.PersonID);
        }
    }

}
// </auto-generated>
