// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tPaketPTConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tPaketPT>
    {
        public tPaketPTConfiguration()
            : this("dbo")
        {
        }

        public tPaketPTConfiguration(string schema)
        {
            ToTable(schema + ".tPaketPT");
            HasKey(x => x.tPaketPTID);

            Property(x => x.tPaketPTID).HasColumnName(@"tPaketPTID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PPTNama).HasColumnName(@"PPTNama").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PPTJam).HasColumnName(@"PPTJam").IsRequired().HasColumnType("int");
            Property(x => x.PPTPersonTotal).HasColumnName(@"PPTPersonTotal").IsRequired().HasColumnType("int");
            Property(x => x.PPTHarga).HasColumnName(@"PPTHarga").IsOptional().HasColumnType("decimal");
            Property(x => x.PPTMasa).HasColumnName(@"PPTMasa").IsOptional().HasColumnType("int");
            Property(x => x.PPTStatus).HasColumnName(@"PPTStatus").IsRequired().HasColumnType("bit");
            Property(x => x.PPTDesc).HasColumnName(@"PPTDesc").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.PPTMembership).HasColumnName(@"PPTMembership").IsRequired().HasColumnType("bit");
        }
    }

}
// </auto-generated>
