// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tPaymentTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tPaymentType>
    {
        public tPaymentTypeConfiguration()
            : this("dbo")
        {
        }

        public tPaymentTypeConfiguration(string schema)
        {
            ToTable(schema + ".tPaymentType");
            HasKey(x => x.PaymentTypeID);

            Property(x => x.PaymentTypeID).HasColumnName(@"PaymentTypeID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NamaType).HasColumnName(@"NamaType").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
        }
    }

}
// </auto-generated>
