// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tPersonConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tPerson>
    {
        public tPersonConfiguration()
            : this("dbo")
        {
        }

        public tPersonConfiguration(string schema)
        {
            ToTable(schema + ".tPerson");
            HasKey(x => x.PersonID);

            Property(x => x.PersonID).HasColumnName(@"PersonID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PNama).HasColumnName(@"PNama").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PTempLahir).HasColumnName(@"PTempLahir").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PTglLahir).HasColumnName(@"PTglLahir").IsOptional().HasColumnType("date");
            Property(x => x.PGender).HasColumnName(@"PGender").IsOptional().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(1);
            Property(x => x.PAlamat).HasColumnName(@"PAlamat").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.PRT).HasColumnName(@"PRT").IsOptional().HasColumnType("nvarchar").HasMaxLength(3);
            Property(x => x.PRW).HasColumnName(@"PRW").IsOptional().HasColumnType("nvarchar").HasMaxLength(3);
            Property(x => x.PKelurahan).HasColumnName(@"PKelurahan").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PKecamatan).HasColumnName(@"PKecamatan").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PKota).HasColumnName(@"PKota").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PPropinsi).HasColumnName(@"PPropinsi").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PIdentitas).HasColumnName(@"PIdentitas").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PEmail).HasColumnName(@"PEmail").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PTelp).HasColumnName(@"PTelp").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PHP1).HasColumnName(@"PHP1").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.PHP2).HasColumnName(@"PHP2").IsOptional().HasColumnType("nvarchar").HasMaxLength(15);
            Property(x => x.PPinBB).HasColumnName(@"PPinBB").IsOptional().HasColumnType("nvarchar").HasMaxLength(10);
            Property(x => x.Id).HasColumnName(@"Id").IsOptional().HasColumnType("nvarchar").HasMaxLength(128);

            HasOptional(a => a.AspNetUser).WithMany(b => b.tPersons).HasForeignKey(c => c.Id);
        }
    }

}
// </auto-generated>
