// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class trAktifitasKelaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<trAktifitasKela>
    {
        public trAktifitasKelaConfiguration()
            : this("dbo")
        {
        }

        public trAktifitasKelaConfiguration(string schema)
        {
            ToTable(schema + ".trAktifitasKelas");
            HasKey(x => x.AktifitasKelasID);

            Property(x => x.AktifitasKelasID).HasColumnName(@"AktifitasKelasID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlanKelasID).HasColumnName(@"PlanKelasID").IsRequired().HasColumnType("int");
            Property(x => x.AktifitasMemberID).HasColumnName(@"AktifitasMemberID").IsOptional().HasColumnType("int");

            HasOptional(a => a.trAktifitasMember).WithMany(b => b.trAktifitasKelas).HasForeignKey(c => c.AktifitasMemberID);
            HasRequired(a => a.trPlanKela).WithMany(b => b.trAktifitasKelas).HasForeignKey(c => c.PlanKelasID);
        }
    }

}
// </auto-generated>
