// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class trAktifitasMemberConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<trAktifitasMember>
    {
        public trAktifitasMemberConfiguration()
            : this("dbo")
        {
        }

        public trAktifitasMemberConfiguration(string schema)
        {
            ToTable(schema + ".trAktifitasMember");
            HasKey(x => x.AktifitasMemberID);

            Property(x => x.AktifitasMemberID).HasColumnName(@"AktifitasMemberID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AMMulai).HasColumnName(@"AMMulai").IsOptional().HasColumnType("datetime");
            Property(x => x.AMSelesai).HasColumnName(@"AMSelesai").IsOptional().HasColumnType("datetime");
            Property(x => x.verifikasiMember).HasColumnName(@"verifikasiMember").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.verifikasiToken).HasColumnName(@"verifikasiToken").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.MemberID).HasColumnName(@"MemberID").IsRequired().HasColumnType("int");
            Property(x => x.PersonBOID).HasColumnName(@"PersonBOID").IsRequired().HasColumnType("int");
            Property(x => x.LocationID).HasColumnName(@"LocationID").IsRequired().HasColumnType("int");
            Property(x => x.ActionPTID).HasColumnName(@"ActionPTID").IsOptional().HasColumnType("int");
            Property(x => x.Status).HasColumnName(@"Status").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(3);

            HasOptional(a => a.tActionPT).WithMany(b => b.trAktifitasMembers).HasForeignKey(c => c.ActionPTID);
            HasRequired(a => a.tLocFitnessCenter).WithMany(b => b.trAktifitasMembers).HasForeignKey(c => c.LocationID);
            HasRequired(a => a.tMember).WithMany(b => b.trAktifitasMembers).HasForeignKey(c => c.MemberID);
            HasRequired(a => a.tUserBackOffice).WithMany(b => b.trAktifitasMembers).HasForeignKey(c => c.PersonBOID);
        }
    }

}
// </auto-generated>
