// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class trEventScoreConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<trEventScore>
    {
        public trEventScoreConfiguration()
            : this("dbo")
        {
        }

        public trEventScoreConfiguration(string schema)
        {
            ToTable(schema + ".trEventScore");
            HasKey(x => x.trEvScoreId);

            Property(x => x.trEvScoreId).HasColumnName(@"trEvScoreId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.trEventStepId).HasColumnName(@"trEventStepId").IsOptional().HasColumnType("int");
            Property(x => x.PersonEventId).HasColumnName(@"PersonEventId").IsOptional().HasColumnType("int");
            Property(x => x.EvScoreId).HasColumnName(@"EvScoreId").IsOptional().HasColumnType("int");
            Property(x => x.Score).HasColumnName(@"Score").IsOptional().HasColumnType("int");

            HasOptional(a => a.tEventScore).WithMany(b => b.trEventScores).HasForeignKey(c => c.EvScoreId);
            HasOptional(a => a.trEventStep).WithMany(b => b.trEventScores).HasForeignKey(c => c.trEventStepId);
            HasOptional(a => a.trPersonEvent).WithMany(b => b.trEventScores).HasForeignKey(c => c.PersonEventId);
        }
    }

}
// </auto-generated>
