// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class trPembayaranConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<trPembayaran>
    {
        public trPembayaranConfiguration()
            : this("dbo")
        {
        }

        public trPembayaranConfiguration(string schema)
        {
            ToTable(schema + ".trPembayaran");
            HasKey(x => x.IDPEMBAYARAN);

            Property(x => x.IDPEMBAYARAN).HasColumnName(@"IDPEMBAYARAN").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TS).HasColumnName(@"TS").IsRequired().IsFixedLength().HasColumnType("timestamp").HasMaxLength(8).IsRowVersion().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);
            Property(x => x.MemberID).HasColumnName(@"MemberID").IsOptional().HasColumnType("int");
            Property(x => x.ID_Transaksi).HasColumnName(@"ID_Transaksi").IsRequired().HasColumnType("int");
            Property(x => x.D_TGL).HasColumnName(@"D_TGL").IsRequired().HasColumnType("datetime");
            Property(x => x.D_JUMLAH).HasColumnName(@"D_JUMLAH").IsOptional().HasColumnType("decimal");
            Property(x => x.PersonBOIDFin).HasColumnName(@"PersonBOIDFin").IsRequired().HasColumnType("int");
            Property(x => x.CC).HasColumnName(@"CC").IsOptional().HasColumnType("decimal");
            Property(x => x.Debit).HasColumnName(@"Debit").IsOptional().HasColumnType("decimal");
            Property(x => x.Cash).HasColumnName(@"Cash").IsOptional().HasColumnType("decimal");
            Property(x => x.TransaksiTipe).HasColumnName(@"TransaksiTipe").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);

            HasOptional(a => a.tMember).WithMany(b => b.trPembayarans).HasForeignKey(c => c.MemberID);
            HasRequired(a => a.tUserBackOffice).WithMany(b => b.trPembayarans).HasForeignKey(c => c.PersonBOIDFin);
        }
    }

}
// </auto-generated>
