// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class trPersonEventConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<trPersonEvent>
    {
        public trPersonEventConfiguration()
            : this("dbo")
        {
        }

        public trPersonEventConfiguration(string schema)
        {
            ToTable(schema + ".trPersonEvent");
            HasKey(x => x.PersonEventId);

            Property(x => x.PersonEventId).HasColumnName(@"PersonEventId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonId).HasColumnName(@"PersonId").IsRequired().HasColumnType("int");
            Property(x => x.EvId).HasColumnName(@"EvId").IsRequired().HasColumnType("int");
            Property(x => x.EvRoleId).HasColumnName(@"EvRoleId").IsRequired().HasColumnType("int");

            HasRequired(a => a.tEvent).WithMany(b => b.trPersonEvents).HasForeignKey(c => c.EvId);
            HasRequired(a => a.tPerson).WithMany(b => b.trPersonEvents).HasForeignKey(c => c.PersonId);
            HasRequired(a => a.tRoleEvent).WithMany(b => b.trPersonEvents).HasForeignKey(c => c.EvRoleId);
        }
    }

}
// </auto-generated>
