// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class trTTDConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<trTTD>
    {
        public trTTDConfiguration()
            : this("dbo")
        {
        }

        public trTTDConfiguration(string schema)
        {
            ToTable(schema + ".trTTD");
            HasKey(x => x.TrTTDID);

            Property(x => x.TrTTDID).HasColumnName(@"TrTTDID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.trMembershipID).HasColumnName(@"trMembershipID").IsOptional().HasColumnType("int");
            Property(x => x.trPTID).HasColumnName(@"trPTID").IsOptional().HasColumnType("int");
            Property(x => x.trTTD_).HasColumnName(@"trTTD").IsOptional().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.MemberID).HasColumnName(@"MemberID").IsRequired().HasColumnType("int");

            HasOptional(a => a.trMembership).WithMany(b => b.trTTDs).HasForeignKey(c => c.trMembershipID);
            HasOptional(a => a.trPersonalTrainer).WithMany(b => b.trTTDs).HasForeignKey(c => c.trPTID);
            HasRequired(a => a.tMember).WithMany(b => b.trTTDs).HasForeignKey(c => c.MemberID);
            HasRequired(a => a.tPerson).WithMany(b => b.trTTDs).HasForeignKey(c => c.MemberID);
        }
    }

}
// </auto-generated>
