// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tRuangKelaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tRuangKela>
    {
        public tRuangKelaConfiguration()
            : this("dbo")
        {
        }

        public tRuangKelaConfiguration(string schema)
        {
            ToTable(schema + ".tRuangKelas");
            HasKey(x => x.RuangKelasID);

            Property(x => x.RuangKelasID).HasColumnName(@"RuangKelasID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NRuangKelas).HasColumnName(@"NRuangKelas").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.BackGround).HasColumnName(@"BackGround").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Map).HasColumnName(@"Map").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Kapasitas).HasColumnName(@"Kapasitas").IsOptional().HasColumnType("int");
        }
    }

}
// </auto-generated>
