// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tStatusMemberPriceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tStatusMemberPrice>
    {
        public tStatusMemberPriceConfiguration()
            : this("dbo")
        {
        }

        public tStatusMemberPriceConfiguration(string schema)
        {
            ToTable(schema + ".tStatusMemberPrice");
            HasKey(x => x.tStatusMemberPriceId);

            Property(x => x.tStatusMemberPriceId).HasColumnName(@"tStatusMemberPriceId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StatusMID).HasColumnName(@"StatusMID").IsRequired().HasColumnType("int");
            Property(x => x.Price).HasColumnName(@"Price").IsRequired().HasColumnType("decimal").HasPrecision(18,2);
            Property(x => x.Period).HasColumnName(@"Period").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(6);

            HasRequired(a => a.tStatusMember).WithMany(b => b.tStatusMemberPrices).HasForeignKey(c => c.StatusMID);
        }
    }

}
// </auto-generated>
