// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DataObjects.Configuration
{
    using DataObjects.Context;
    using DataObjects.Entities;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class tUserBackOfficeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<tUserBackOffice>
    {
        public tUserBackOfficeConfiguration()
            : this("dbo")
        {
        }

        public tUserBackOfficeConfiguration(string schema)
        {
            ToTable(schema + ".tUserBackOffice");
            HasKey(x => x.PersonBOID);

            Property(x => x.PersonBOID).HasColumnName(@"PersonBOID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BOIDNO).HasColumnName(@"BOIDNO").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.StatusBOID).HasColumnName(@"StatusBOID").IsRequired().HasColumnType("bit");
            Property(x => x.BMulai).HasColumnName(@"BMulai").IsRequired().HasColumnType("date");
            Property(x => x.BFoto).HasColumnName(@"BFoto").IsOptional().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.BFotoKTP).HasColumnName(@"BFotoKTP").IsOptional().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.BFotoSignature).HasColumnName(@"BFotoSignature").IsOptional().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.BRFID).HasColumnName(@"BRFID").IsOptional().HasColumnType("nvarchar");
            Property(x => x.PosisiID).HasColumnName(@"PosisiID").IsRequired().HasColumnType("int");
            Property(x => x.Background).HasColumnName(@"Background").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);

            HasRequired(a => a.tPerson).WithOptional(b => b.tUserBackOffice);
            HasRequired(a => a.tPosisi).WithMany(b => b.tUserBackOffices).HasForeignKey(c => c.PosisiID);
        }
    }

}
// </auto-generated>
